### ISSUE TITLE
Policy for allowing starting/stopping of services

### ISSUE THREAD

**Issue by ykhodorkovskiy** [TresysTechnology/clip#190]
This is the parent issue for systemctl policy. To see enabled services, run
` systemctl list-unit-files -t service|grep enabled`

The following services exist, and if checked, don't need or already have valid policy.

- [x] auditd.service #194
- [x] chronyd.service #193
- [x] crond.service #195
- [x] dbus-org.fedoraproject.FirewallD1.service #196
- [x] firewalld.service #191 
- [x] getty\@tty1.service  #200
- [x] lvm2-monitor.service #197
- [x] rsyslog.service #198
- [x] sshd.service #192 
- [ ] systemd-readahead-collect.service 
- [ ] systemd-readahead-drop.service #199
- [ ] systemd-readahead-replay.service

**Comment by mpalmi** [comment]
Updated subtickets as appropriate.
All services seem to start/stop without issue, with the exception of firewalld.

Some notes:
- firewalld still seems to stop/start (verified with `systemctl status firewalld.service`), but appears to do so with errors in Enforcing.
- I am able to run `systemctl status foo.service` as well.
- I am currently unable to run `systemctl list-units`. Additionally, I do not get denials when running `systemctl list-units` in Permissive (which works), even after rebuilding a non-dontaudit policy `semodule -DB`. I do not see any "suppressed" messages, and have attempted flushing out the policy, in the event that the denial was hitting the cache and just not displaying.
- Testing was done on a Permissive build by first `sudo`ing and then switching to Enforcing.
- We are still not able to `sudo` in Enforcing.

**Comment by ykhodorkovskiy** [comment]
Thanks @mpalmi. And I agree about sshd, I will close that issue out now.

**Comment by ykhodorkovskiy** [comment]
@mpalmi Should we check for any denials on boot with systemd-readahead*?

**Comment by mpalmi** [comment]
@ykhodorkovskiy yeah, I don't think I saw any for drop, but I'm not sure about start/status. Worth a check.
