### ISSUE TITLE
Get CLIP RHEL7 Booting in Enforcing

### ISSUE THREAD

**Issue by mpalmi** [TresysTechnology/clip#86]
The first step in addressing #4 is to get CLIP booting in Enforcing.

With the new systemd architecture, there are some significant changes to the way processes spawn.
We will need to pull in Chris PeBenito's changes to the RHEL7 updates to refpolicy (https://github.com/pebenito/refpolicy), specifically the following commits:
* https://github.com/pebenito/refpolicy/commit/0872c57885bf540574a42eb0c22314281bd97549 -> adding to the list of permissions for the service class,
add service class to security classes, update various init module interfaces with ifdefs for init_systemd
* https://github.com/pebenito/refpolicy/commit/e56024d2aaf00326f8e3b6b6bd327d053ec29294 -> allow dynamic transition from kernel domain to init for ifdef
init_systemd
* https://github.com/pebenito/refpolicy/commit/505158a7ad9f22c1f537f50db6b48b8391f24548 -> On Debian, systemd binaries are installed in / not /usr
* https://github.com/pebenito/refpolicy/commit/c93002d65dfd4d8b622f0cb51b7f8ef15cb55f91 -> Drop bin_t label for /lib/systemd/systemd.*
* https://github.com/pebenito/refpolicy/commit/98963454cbe2f5beb3a4884b46c8953ca2a31a4f -> Merge pull request #1 from bigon/systemd
* https://github.com/pebenito/refpolicy/commit/52273366f28e5e63b9742b8c0605ebf2585e9710 -> More systemd apps cleanup
* https://github.com/pebenito/refpolicy/commit/9f1fc533c2a1adebaa57efe0e04192a3f14e7e15 -> Run the misc initializations that systemd does in initrc_t

From there, it is a matter of typical policy development. Gather denials, write policy, wash, rinse, repeat.

----

As of 4/22, we are able to boot in Enforcing with several  permissive domains:
tomhurd/clip@646f163
tomhurd/clip@498ddcd

We really only need a subset of these to be permissive, however:
- kernel_t
- initrc_t
- init_t
- syslogd_t
- lvm_t
- udev_t 

The future efforts will be driven by pulling all domains out of permissive, but for the sake of getting CLIP booting in Enforcing, the following are the priority:
- [ ] #126 - Pull kernel_t out of Permissive
- [x] #127 - Pull initrc_t out of Permissive
- [ ] #118 - Pull init_t out of Permissive
- [x] #129 - Pull syslogd_t out of Permissive
- [x] #128 - Pull lvm_t out of Permissive
- [x] #130 - Pull udev_t out of Permissive

To get CLIP *cleanly* booting in Enforcing, the following will need to be done as well:
- [x] #132 - Pull insmod_t out of Permissive.
- [ ] #131 - Pull local_login_t out of Permissive
- [ ] #150 - Pull systemd_tmpfiles out of Permissive

Some nice-to-haves (not necessarily needed to get CLIP booting in Enforcing):
- [ ] #134 - Pull toor_t out of Permissive
- [ ] #135 - Pull sshd_keygen_t out of Permissive

**Comment by mpalmi** [comment]
Rather than cherry-pick commits, we have updated the base refpolicy to https://github.com/pebenito/refpolicy/commit/5fd2953d9951cbaa15ff73b24ae8ec52e1ca06ee

Further development is being done on top of this to get CLIP booting in Enforcing.

**Comment by ykhodorkovskiy** [comment]
@mpalmi please assign a time estimate label for this issue.

**Comment by mpalmi** [comment]
We are currently able to boot in Enforcing, using several permissive domains.
The future tasks will be focused on taking these domains out of permissive.

See:
tomhurd/clip@646f163a515abbcb3de81412eb1a360b099333f6
tomhurd/clip@498ddcd9c8af617365a1f9534d8c75b012bbc64d

**Comment by mpalmi** [comment]
Though we're booting in Enforcing, there are still some lingering denials.
Attached are the errors that are seen on boot
![image](https://cloud.githubusercontent.com/assets/7817675/7776716/165701b0-008b-11e5-93cf-838372f90062.png)

Potentially related to denials seen in:
#118
#130
#164
#126
#128

**Comment by tomhurd** [comment]
The /lib/systemd/rhel-autorelabel problem is related to issue #127.

I expect the contexts that aren't valid are from rhel targeted policy and not in the clip policy.

**Comment by mpalmi** [comment]
Closing the master ticket for now, even though all subtickets are not completely resolved. Will open future tickets to fix issues found in testing.
